### ISSUE TITLE
About Voice Guide Function

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#14]
It is requested to add a new function for Voice Guide.

- Add a switch to turn on/off the Voice Guide. (Finished)
- When the Voice Guide is on, within 3 meters to the destination, open the Voice Guide view, and it should display and read out the description.
- The Voice Guide should include those functions: pause, roll back, read speed control.

For the second step, I found the source code for `didNavigationFinished`. The description text is read out after arriving, but I could not find the text.

The distance before arriving is read out as well, but I failed to find out the source code executing the TTS function.

I have checked about the navigator's interface. Please let me know if there is a proper function that I can use. Thank you.

**Comment by daisukes** [comment]
https://github.com/miraikan-research/NavCog-Miraikan/blob/70c7f7434037abb21168f4d819d11c0bf92bcd7e/NavCog3/blind/NavCommander.m#L566

Please check here. All the announcements for the blind navigation are produced in this clss.

**Comment by hiroshi-shin** [comment]
Thank you for the explanation.

Finally, I found it in `pois`.
