### ISSUE TITLE
対話検索関連の問題

### ISSUE THREAD

**Issue by HiroTakagi** [miraikan-research/NavCog-Miraikan#18]
- VoiceOverを使用中に対話検索を起動しても音声入力ができない。音声が認識されない。
- 音声対話のTTS音声の音量が非常に小さい。

**Comment by hiroshi-shin** [comment]
未来館アプリに色々試したが、NavCog3 と比較すると、同じ問題も発生しました。

hulop に issue を作成しました。

https://github.com/hulop/NavCogIOSv3/issues/61

**Comment by daisukes** [comment]
HLPDialogのswift-packageにバグフィックスをコミットしました。
確認をお願いします。

https://github.com/hulop/HLPDialog/issues/1

**Comment by hiroshi-shin** [comment]
@daisukes 

音量、音声認識両方も解決できました。

ありがとうございます。
