### ISSUE TITLE
HLPDialog not starting

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#2]
**Summary**

In NavCog3, the `HLPDialog` works fine when I open it from Voice Search.

However, when I tried to instantiate it from storyboard or create a new instance, and open it from a customized tab, the view state was always inactive. It had no sound, while the voice input was not received.

![IMG_0169](https://user-images.githubusercontent.com/87963922/143392673-06a948d0-7ebf-45a5-82e1-b21972f21562.PNG)

**Source code**
https://github.com/miraikan-research/NavCog-Miraikan/blob/bf95df50ae63a478c329acf2de4b292df855ca02/Miraikan/Utils/Model.swift#L81-L91

Besides that, I also tried to call  the `action()`, and check about other statements that using `[DialogManager sharedManager]`.

Please let me know if I missed any settings. Thank you.

**Comment by daisukes** [comment]
You need to set [tts](https://github.com/hulop/HLPDialog/blob/11bb6937f06ac6e7deaa7fd85d48a320fbe813aa/HLPDialog/DialogViewController.swift#L59) member of DialogViewController.

In the original code, DefaultTTS is used for the tts. However, there will be a cyclic reference problem if you try to use DefaultTTS(in objective c, which refers to swift) from swift code.
Fortunately, DefaultTTS is a very small code, you can translate it into swift.

https://github.com/daisukes/NavCog-Miraikan/tree/dev-dialog-bugfix

I also fixed an issue with HLPDialog, which happens with iOS15 and newer devices.
You may need to update HLPDialog to avoid the issue.

**Comment by hiroshi-shin** [comment]
Thank you very much for the update. Now the TTS is working.

Actually, I tried to create my own version, but failed with incorrect inheritance.
```
class VoiceSearchController: DialogViewController, TTSProtocol {
    
    init() {
        super.init(nibName: nil, bundle: nil)
        self.tts = self
    }
   ...
}
```

![Screen Shot 2021-11-26 at 18 07 41](https://user-images.githubusercontent.com/87963922/143555620-e20be568-0ac1-4a0f-9998-343454b3839e.png)

In addition, in order to start navigation after the conversation, it might be necessary to create a class inheriting `DialogViewController` and call the `speak()` function with a callback.

I have checked about `DialogViewController` as well as other controllers that using TTS, but I failed to find one that opening the map. Is there any source code I can refer to? Thank you.

**Comment by daisukes** [comment]
maybe `import HLPDialog`?


At the end of conversation, it posts a notification. 
https://github.com/hulop/HLPDialog/blob/a2dd24cbaf56a3d8c32b89f2e3c41f1fc6f84691/HLPDialog/DialogViewController.swift#L674

You can refer here to handle the notification.
https://github.com/hulop/NavCogIOSv3/blob/a25a85834ffb9644025692a69c91c26264a196ac/NavCog3/SearchViewController.m#L68

**Comment by hiroshi-shin** [comment]
Thank you for the answer.

Now I understand where is `- (void)requestStartNavigation:(NSNotification*)note` used.
