### ISSUE TITLE
Wiki Media

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#25]
**UI Overview**

![ui_overview](https://user-images.githubusercontent.com/87963922/147447079-caba0fbd-5e74-4fd7-9cc6-02bb799c93c0.gif)

**Blind Mode**

![ui_blind](https://user-images.githubusercontent.com/87963922/147447203-1ee07e6f-8ae7-48de-a4ef-8cfa544ce110.gif)

**Navi Settings**

![navi_setting](https://user-images.githubusercontent.com/87963922/147447589-7370dd11-9628-44ac-840e-1545f73dadc2.PNG)

**AI Dialog**

![ask_ai](https://user-images.githubusercontent.com/87963922/147452554-1f899282-a7b6-465c-a5ac-80f8fbd9a26a.gif)

**Icons**

![IMG_0264](https://user-images.githubusercontent.com/87963922/147447671-63d73e76-dba7-4390-989b-a638ed9f7348.jpeg)

**Comment by hiroshi-shin** [comment]
### Miraikan in English

**UI**

![ui_en](https://user-images.githubusercontent.com/87963922/147321995-9aed85ea-ef95-4a6c-b616-64aaa1304bfa.gif)

**Voice Guide**

![voice_guide_en](https://user-images.githubusercontent.com/87963922/147322021-ec3e3450-b35e-43b9-9cc2-72c74f87a61f.gif)

**WebView**

![web_en](https://user-images.githubusercontent.com/87963922/147322070-7d33dbc7-39e9-4ceb-be14-8cfd79f063a1.gif)

**Comment by ryo-yoshizawa-lab** [comment]
2021年12月以前の実装
何を問題にしているのか不明であるが、画面自体が古く、レイアウト設定も見直したため、クローズとする
