### ISSUE TITLE
到着判定が行われない

### ISSUE THREAD

**Issue by ryo-yoshizawa-lab** [miraikan-research/NavCog-Miraikan#37]
視覚障がい者でも、到着時に音声案内があったり、何も動作しないことがある。
到着時のアクションが安定しない

**Comment by HiroTakagi** [comment]
@ryo-yoshizawa-lab 測位がずれていることが原因でしょうか？

**Comment by ryo-yoshizawa-lab** [comment]
根本的に当初のナビゲーション処理が間違っていたため、別の処理に修正済み
到着判定は行われるようになりました。
