### ISSUE TITLE
ホーム：場所の情報がないイベントは場所を表示しない

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#5]
https://github.com/miraikan-research/app_tasks/issues/32

**Comment by HiroTakagi** [comment]
これは完了でしょうか？ @hiroshi-shin

**Comment by hiroshi-shin** [comment]
変更後の結果ですが、

- ホーム画面：場所の情報がないイベントに「場所」を表示しない。
- 詳細画面：現時点に館内の位置は記載されていない、オンラインの判定のみ存在しているので、ナビボタンを表示しない。
- その他：当日にイベントのない場合、説明文言を表示する。

上記のまま理解していますけど、もし勘違いしましたら、ご説明をお願いします。

**Comment by HiroTakagi** [comment]
了解です。クローズします。
