### ISSUE TITLE
実装されていない機能がわかるようにする

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#6]
https://github.com/miraikan-research/app_tasks/issues/31

**Comment by HiroTakagi** [comment]
実装されていない機能がグレーになったのですがVoiceOverで読み上げられなくなりました。
読み上げられるようにしてください

https://user-images.githubusercontent.com/84007414/145022911-86f8601d-5a61-4247-8a86-a6e9d5cf0f25.mov

**Comment by HiroTakagi** [comment]
このように白地にグレーでお願いします。
![image](https://user-images.githubusercontent.com/84007414/145028355-d82fe12b-3f39-4068-b590-2aae8d62e0e9.png)
