### ISSUE TITLE
VoiceOver: イベントページを開いた時、webページが開く前は存在がわからない

### ISSUE THREAD

**Issue by hiroshi-shin** [miraikan-research/NavCog-Miraikan#7]
https://github.com/miraikan-research/app_tasks/issues/29

**Comment by hiroshi-shin** [comment]
**実装結果**

- 読込中：読込中のメッセージが表示される。
- 読込成功：読込中のメッセージが隠れて、VoiceOver にもアクセスできない。
- 読込成功：読込失敗のメッセージが表示される。

**Comment by HiroTakagi** [comment]
#21

**Comment by ryo-yoshizawa-lab** [comment]
イベントページ自体が項目として、無くなるため、クローズ
